name: SuperMode
version: 2.0
author: PedroIsBored
main: com.pearrudas.Main
api-version: 1.13

commands:
   supermode:
      description: Main command, displays plugin version.
      usage: /supermode <help/toggle/list> (player)